options:
  formatter: stylish
  merge-default-rules: true
  cache-config: true

files:
  include: '**/*.s+(a|c)ss'
  ignore: 'node_modules/**/*.s+(a|c)ss'

rules:
  no-ids: 1
  no-mergeable-selectors: 2
  no-trailing-whitespace: 2
  force-pseudo-nesting: 0
  property-sort-order: 0
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  no-color-literals: 1
  no-important: 2
  no-url-domains: 1
  quotes:
    - 1
    - style: single
  space-after-colon:
    - 1
    - include: true
  space-before-brace:
    - 0
    - include: false
  space-before-colon:
    - 1
    - include: false
  trailing-semicolon: 1
  no-misspelled-properties: 0
  empty-line-between-blocks: 1
  no-vendor-prefixes: 0
  nesting-depth:
    - 1
    - max-depth: 5
