name: Sith4 linting

on:
  pull_request: 
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      
      - name: Install pnpm
        run: npm install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint
