name: Run tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm ng test --watch false

      - name: Export coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Coverage results
          path: coverage
          retention-days: 7

  # todo: add e2e tests
  # Should run on all OSes (Windows, Linux, macOS)
